<?php

// Includes functions to create Islandora Solr blocks.
require_once dirname(__FILE__) . '/includes/blocks.inc';
require_once dirname(__FILE__) . '/includes/utilities.inc';
require_once dirname(__FILE__) . '/includes/doi_importer.inc';
require_once dirname(__FILE__) . '/includes/wos.inc';
require_once dirname(__FILE__) . '/includes/kuali.inc';
require_once dirname(__FILE__) . '/includes/citeproc_converter.inc';
// require_once dirname(__FILE__) . '/theme/theme.inc';
module_load_include('inc', 'opensky', 'theme/theme');

/**
 * Implements hook_menu().
 */
function opensky_menu () {
    $items = array();
    $items['opensky/scratch'] = array(
        'title' => 'OpenSky Scratch',
        'page callback' => 'opensky_scratch',
        'access callback' => TRUE,
        'expanded' => TRUE,
    );
    return $items;
}

// Implement hook_theme_registry_alter
function opensky_theme_registry_alter(&$theme_registry) {

    if (!empty($theme_registry['islandora_solr_metadata_display'])) {
        $theme_registry['islandora_solr_metadata_display']['template'] = drupal_get_path('module', 'opensky') . '/theme/opensky-solr-metadata-display'; 
    }
    if (!empty($theme_registry['islandora_basic_collection_wrapper'])) {

        $theme_registry['islandora_basic_collection_wrapper']['template'] = drupal_get_path('module', 'opensky') . '/theme/opensky-basic-collection-wrapper'; 


        if ($theme_registry['islandora_basic_collection_wrapper']['preprocess functions'][1] != 'template_preprocess_opensky_basic_collection_wrapper') {
            array_splice ($theme_registry['islandora_basic_collection_wrapper']['preprocess functions'], 1, 0, 'template_preprocess_opensky_basic_collection_wrapper');
        }        
    }
    //    dpm ($theme_registry['islandora_basic_collection_wrapper']);
}

/**
 * Implements hook_theme().
 */
function opensky_theme() {
    $path = drupal_get_path('module', 'opensky');
    $file = 'theme.inc';
    return array (
        'opensky_scratch' => array (
            'path' => $path . '/theme',
            'file' => $file,
            'template' => 'opensky-scratch',
            'variables' => array ('pid' => null),
        ),
        'opensky_search_collection_info' => array (
            'path' => $path . '/theme',
            'file' => $file,
            'template' => 'opensky-search-collection-info',
            'variables' => array (
                'collection_pid' => NULL,
                'collection_title' => NULL,
                'collection_description' => NULL
            ),
        ),
        'opensky_in_collections' => array(
            'path' => $path . '/theme',
            'file' => $file,
            'template' => 'opensky-in-collections',
            'variables' => array (
                'parent_collections' => NULL,
            ),
        ),
        'opensky_advanced_search' => array(
            'path' => $path . '/theme',
            'file' => $file,
            'template' => 'opensky-advanced-search',
            'variables' => array (
                'collection_pid' => NULL,
            ),
        ),
        'opensky_collection_picker_data' => array (
            'path' => $path . '/theme',
            'file' => $file,
            'template' => 'opensky-collection-picker-data',
            'variables' => array (
                'option_data' => NULL,
            ),
        ),
        'opensky_solr_metadata_display' => array (
            'path' => $path . '/theme',
            'file' => $file,
            'template' => 'opensky-solr-metadata-display',
            'variables' => array (
                'option_data' => NULL,
            ),
        ),
        'opensky_basic_collection_wrapper' => array (
            'path' => $path . '/theme',
            'file' => $file,
            'template' => 'opensky-basic-collection-wrapper',
            'variables' => array (
                'option_data' => NULL,
            ),
        ),
    );
}

/**
 * Implements hook_help().
 */
function opensky_help($path, $arg) {

    if ($path == 'admin/help#opensky') {
        $output = '<h3>' . t('About') . '</h3>';
        $output .= '<p>' . t('The opensky module provides extensions and customization to Islandora core modules.') . '</p>';
        return $output;
    }
}

/**
 * Provide content for the opensky/scratch page (via opensky_scratch theme)
 */
function opensky_scratch() {

    $defaultpid = 'archives:hao';
    $pid = isset($_GET['pid']) ? $_GET['pid'] : $default_pid;

    return theme('opensky_scratch', array('pid' => $pid));
}
